### ISSUE TITLE
Post title not centering at small screen sizes

### ISSUE THREAD

**Issue by jaredh159** [netrivet/prophoto-issues#194]
Fix should be:

```CSS
.article-header.is-aligned-center .article-title {
  text-align: center;
}
```
